---
- name: Deploy postgres backup
  docker_container:
    name: postgres_backup
    image: prodrigestivill/postgres-backup-local
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: sonarqube_net
    volumes:
      - "{{path}}/database/data:/backups"
    env:
      POSTGRES_HOST: postgres
      POSTGRES_USER: "{{ postgres_username }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "{{db_name}}"
      SCHEDULE: "@hourly"
      BACKUP_KEEP_DAYS: "7"
      BACKUP_KEEP_WEEKS: "4"
      BACKUP_KEEP_MONTHS: "6"
      HEALTHCHECK_PORT: "8080"
